### ISSUE TITLE
Export messages_processed filled with all topics instead of only cva and rcrc

### ISSUE THREAD

**Issue by p-phung** [rodekruis/rumor-tracker#11]
All categories as headers besides RC and CVA in the processed messages file instead of in separate files. 
Each messages will be filled with score for all categories. Only for RC and CVA will remain True/False.

**Comment by jmargutt** [comment]
https://github.com/rodekruis/rumor-tracker/commit/68339f02fffaf10b978a4e83e5ab6131e001a79b
